### PR TITLE
Can now upload pdf to the block chain

### PR DESCRIPTION
**Pull request by imalexhu**
Can now automatically store any  pdf onto the blockchain.

payloads are split into 3kib chunks, and uploaded to the blockchain accordingly

### CODE REVIEW

**Comment by imalexhu** [comment]
#5

**Comment by pearlyna01** [comment]
Missing ";" at the end of some lines.

**Comment by pearlyna01** [comment]
missing ";" in hedera.js and server.js

**Review by magicusingjunta — APPROVED** [review]
watch consistency with ; at end of statements (eg. line 45 vs line 104, line 115 vs line 116)

**Pull request merged**
