### PR TITLE
nav bar 

### PR DESCRIPTION
**Pull request by pearlyna01**
Made 2 kinds of nav bar. Top and side.

### CODE REVIEW

**Comment by pearlyna01** [comment]
Top navigation bar. Just links in the nav bar

**Comment by pearlyna01** [comment]
Working on dropdown menu for phone view

**Review by wendyla — APPROVED** [review]
Looks really good!

**Review by jennyytran — APPROVED** [review]

**Review by wendyla — APPROVED** [review]
Approved

**Pull request merged**
